import { writeFile } from 'node:fs/promises';
import { BOOK_CATALOG } from '../functions/_catalog.js';
import { PDF_CANDIDATE_OVERRIDES } from '../functions/_pdf_candidates.js';

const CONCURRENCY = 8;
const TIMEOUT_MS = 20000;

async function candidateFor(book) {
  const override = PDF_CANDIDATE_OVERRIDES[book.catalog_id];
  if (override?.url) return override.url;
  if (override?.source_page) {
    try {
      const page = await fetch(override.source_page, {
        redirect: 'follow',
        headers: { 'user-agent': 'Mozilla/5.0 Haydari-Workbench-PDF-Discovery/1.0' },
        signal: AbortSignal.timeout(TIMEOUT_MS),
      });
      if (page.ok) {
        const html = await page.text();
        const matches = [...html.matchAll(/https:\/\/download\.almohsinlibrary\.com\/[^"'<>\\s]+?\.pdf(?:\?[^"'<>\\s]*)?/gi)];
        if (matches.length) return matches[0][0].replaceAll('&amp;', '&');
      }
    } catch {}
  }
  return book.pdf_url || null;
}

async function verifyPdf(url) {
  if (!url) return { status: 'missing', final_url: null, note: 'No direct PDF candidate' };

  let response;
  try {
    response = await fetch(url, {
      method: 'GET',
      redirect: 'follow',
      headers: {
        'range': 'bytes=0-15',
        'user-agent': 'Haydari-Workbench-PDF-Audit/1.0'
      },
      signal: AbortSignal.timeout(TIMEOUT_MS),
    });
  } catch (error) {
    return {
      status: 'unchecked',
      final_url: null,
      note: `Deferred after fetch failure: ${error?.name || 'Error'}`,
    };
  }

  const finalUrl = response.url || url;
  const type = (response.headers.get('content-type') || '').toLowerCase();

  if (response.status === 404 || response.status === 410) {
    try { await response.body?.cancel(); } catch {}
    return { status: 'missing', final_url: null, note: `HTTP ${response.status}` };
  }

  if (response.status === 429 || response.status >= 500) {
    try { await response.body?.cancel(); } catch {}
    return {
      status: 'unchecked',
      final_url: null,
      note: `Deferred: HTTP ${response.status}`,
    };
  }

  if (!response.ok && response.status !== 206) {
    try { await response.body?.cancel(); } catch {}
    return { status: 'missing', final_url: null, note: `HTTP ${response.status}` };
  }

  let first = new Uint8Array();
  try {
    const reader = response.body?.getReader();
    if (reader) {
      const chunk = await reader.read();
      first = chunk.value || new Uint8Array();
      try { await reader.cancel(); } catch {}
    }
  } catch (error) {
    return {
      status: 'unchecked',
      final_url: null,
      note: `Deferred during PDF validation: ${error?.name || 'Error'}`,
    };
  }

  const magic = new TextDecoder('latin1').decode(first.slice(0, 5));
  const isPdf = type.includes('application/pdf') || magic.startsWith('%PDF-');
  if (!isPdf) {
    return { status: 'missing', final_url: null, note: `Not a PDF (content-type: ${type || 'unknown'})` };
  }

  return {
    status: 'available',
    final_url: finalUrl,
    note: `Verified PDF: HTTP ${response.status}; ${type || 'PDF magic'}`,
  };
}

const results = {};
let cursor = 0;

async function worker() {
  while (true) {
    const i = cursor++;
    if (i >= BOOK_CATALOG.length) return;
    const book = BOOK_CATALOG[i];
    const candidate = await candidateFor(book);
    const verified = await verifyPdf(candidate);
    results[book.catalog_id] = {
      title_ar: book.title_ar,
      candidate_url: candidate,
      status: verified.status,
      url: verified.final_url,
      checked_at: new Date().toISOString(),
      note: verified.note,
    };
    process.stdout.write(`[${i + 1}/${BOOK_CATALOG.length}] ${book.catalog_id} ${verified.status}\n`);
  }
}

await Promise.all(Array.from({ length: CONCURRENCY }, worker));

const ordered = Object.fromEntries(
  BOOK_CATALOG.map(book => [book.catalog_id, results[book.catalog_id]])
);

const available = Object.values(ordered).filter(x => x.status === 'available').length;
const missing = Object.values(ordered).filter(x => x.status === 'missing').length;
const unchecked = Object.values(ordered).filter(x => x.status === 'unchecked').length;
const version = `audit-${new Date().toISOString()}-${available}ok-${missing}missing-${unchecked}unchecked`;

const js = `// Generated by workbench/scripts/audit-pdfs.mjs. Do not hand-edit.\nexport const PDF_AUDIT_VERSION = ${JSON.stringify(version)};\nexport const PDF_AUDIT = ${JSON.stringify(ordered, null, 2)};\n`;
const json = JSON.stringify({ version, available, missing, unchecked, books: ordered }, null, 2) + '\n';

await writeFile(new URL('../functions/_pdf_audit.js', import.meta.url), js);
await writeFile(new URL('../public/pdf-audit.json', import.meta.url), json);
console.log(`PDF audit complete: ${available} available, ${missing} missing, ${unchecked} unchecked`);
