-- Haydari Translation Platform — PostgreSQL schema (production).
-- Ported from schema.sql (SQLite). Kept row-for-row compatible so the same
-- db.py query functions work against either backend:
--   * INTEGER PRIMARY KEY AUTOINCREMENT  -> BIGINT GENERATED ... AS IDENTITY
--   * strftime(...) TEXT default         -> to_char(now(), ISO-8601) TEXT default
--   * BLOB                               -> BYTEA
--   * REAL                               -> DOUBLE PRECISION
--   * (no PRAGMA; Postgres enforces FKs and uses MVCC)
-- Timestamps remain ISO-8601 UTC TEXT strings, identical to the SQLite side.

CREATE TABLE IF NOT EXISTS books (
    id             TEXT PRIMARY KEY,
    title_ar       TEXT NOT NULL,
    title_en       TEXT,
    author         TEXT,
    status         TEXT NOT NULL DEFAULT 'draft',
    source_pdf     TEXT,
    google_doc_url TEXT,
    pages_total    INTEGER NOT NULL DEFAULT 0,
    translation_notes TEXT,
    updated_at     TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

CREATE TABLE IF NOT EXISTS pages (
    book_id       TEXT NOT NULL,
    page_no       INTEGER NOT NULL,
    image_path    TEXT,
    ocr_markdown  TEXT,
    status        TEXT NOT NULL DEFAULT 'draft',
    PRIMARY KEY (book_id, page_no),
    FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS segments (
    id                TEXT PRIMARY KEY,
    book_id           TEXT NOT NULL,
    page_no           INTEGER NOT NULL,
    seg_order         INTEGER NOT NULL,
    kind              TEXT NOT NULL DEFAULT 'body'
                          CHECK (kind IN ('body', 'footnote', 'sacred')),
    anchor            TEXT,
    ar                TEXT NOT NULL,
    en_draft          TEXT,
    en_current        TEXT,
    engine            TEXT,
    confidence        DOUBLE PRECISION,
    bt_sim            DOUBLE PRECISION,
    self_consistency  DOUBLE PRECISION,
    judge_score       DOUBLE PRECISION,
    judge_note        TEXT,
    footnote_ok       INTEGER,
    alternatives      TEXT,
    status            TEXT NOT NULL DEFAULT 'draft'
                          CHECK (status IN ('draft', 'needs_review', 'approved')),
    updated_at        TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE,
    FOREIGN KEY (book_id, page_no) REFERENCES pages(book_id, page_no) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_segments_book_page ON segments (book_id, page_no, seg_order);
CREATE INDEX IF NOT EXISTS idx_segments_status ON segments (status);

CREATE TABLE IF NOT EXISTS translation_memory (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id      TEXT,
    ar_hash      TEXT NOT NULL,
    ar           TEXT NOT NULL,
    en_approved  TEXT NOT NULL,
    embedding    BYTEA,
    created_at   TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tm_book_arhash
    ON translation_memory (COALESCE(book_id, ''), ar_hash);

CREATE TABLE IF NOT EXISTS termbase (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    term_ar     TEXT NOT NULL,
    term_en     TEXT NOT NULL,
    note        TEXT,
    scope       TEXT NOT NULL DEFAULT 'global' CHECK (scope IN ('global', 'book')),
    book_id     TEXT,
    created_by  TEXT,
    created_at  TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_termbase_scope ON termbase (scope, book_id);
CREATE INDEX IF NOT EXISTS idx_termbase_term_ar ON termbase (term_ar);

CREATE TABLE IF NOT EXISTS style_rules (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule        TEXT NOT NULL,
    scope       TEXT NOT NULL DEFAULT 'global' CHECK (scope IN ('global', 'book')),
    book_id     TEXT,
    created_at  TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_style_rules_scope ON style_rules (scope, book_id);

CREATE TABLE IF NOT EXISTS corrections (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    segment_id     TEXT NOT NULL,
    en_before      TEXT,
    en_after       TEXT,
    diff_json      TEXT,
    mqm_tags_json  TEXT,
    dims_json      TEXT,
    reviewer       TEXT,
    created_at     TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    FOREIGN KEY (segment_id) REFERENCES segments(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_corrections_segment ON corrections (segment_id);

CREATE TABLE IF NOT EXISTS events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts           TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    actor        TEXT,
    type         TEXT NOT NULL,
    payload_json TEXT
);

CREATE INDEX IF NOT EXISTS idx_events_type ON events (type);
CREATE INDEX IF NOT EXISTS idx_events_ts ON events (ts);
